version: '3.9'

services:
  mysql: 
    image: mysql:8.0.30
    restart: always
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-defaultpassword}
    volumes:
      - "${MYSQL_DATA_PATH:-./data/mysql}:/var/lib/mysql"
    networks:
      mysql-network:
        ipv4_address: ${MYSQL_NETWORK_IP:-172.30.1.1}

networks:
  mysql-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
