version: '3.9'
services: 
  redis:
    image: redis:7.0.9
    container_name: redis7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-defaultpassword} --port ${REDIS_PORT:-6379}
    ports: 
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - "${REDIS_DATA_PATH:-./data/redis}:/var/lib/redis/data"
    networks:
      redis-network:
        ipv4_address: ${REDIS_NETWORK_IP:-172.30.2.1}

networks:
  redis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
