version: '3.9'

services:
  kafka:
    image: bitnami/kafka:4.0
    container_name: kafka
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT:-9092}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "${KAFKA_DATA_PATH:-./data/kafka}:/bitnami/kafka"
    networks:
      kafka-network:
        ipv4_address: ${KAFKA_NETWORK_IP:-172.30.3.1}

networks:
  kafka-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
